### ISSUE TITLE
NUDT-SIRST 会公开吗？

### ISSUE THREAD

**Issue by q671383789** [YeRen123455/Infrared-Small-Target-Detection#10]
你好，请问一下NUDT-SIRST数据集会公开吗？ 如果会的话，大概什么时候呢，谢谢

**Comment by YeRen123455** [comment]
非常抱歉，目前审稿人还在对数据集提新的意见，我们将在审稿结束后，第一时间公开数据集。

**Comment by q671383789** [comment]
@YeRen123455  你好，昨天在NUAA上的数据集跑了一下，发现在原始的数据集分类上（300+训练 86测试）上的结果并没有文中提到的那么高，最好的结果IoU大概在73左右，请问是哪里设置不对嘛

**Comment by q671383789** [comment]
还有就是在这个数据集上，结果波动会很大，就算是最好的结果，每次也会有1~2个点的波动，请问文章的结果是多次实验取平均还是取多次的最好结果

**Comment by YeRen123455** [comment]
你好，请问用的是DNANet吗，超参数是否和原文设置一致

**Comment by q671383789** [comment]
不是，base和crop size改成了512，数据集是用的最原始的split ,不是你们这个50-50，最高的点是75.3左右。1500epoch，我在单3090上跑 好想有点费时间，感觉后期其实没有什么变化了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月23日(星期四) 晚上10:24
收件人: ***@***.***&gt;; 
抄送: "系要听Rock &amp; ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YeRen123455/Infrared-Small-Target-Detection] NUDT-SIRST 会公开吗？ (Issue #10)





 
你好，请问用的是DNANet吗，超参数是否和原文设置一致
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YeRen123455** [comment]
我仔细翻看了实验记录，取得77%左右的mIoU是不困难的，NUAA-SIRST 数据集比较小，1~2%的波动很正常，建议采用原文默认实验设置。

**Comment by q671383789** [comment]
好的，谢谢，主要是我自己做实验是在512上做的，想进行有效的对比。我一般300个epoch每次实验的最好结果都会有点差别，老是在74~76之间波动




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月23日(星期四) 晚上10:30
收件人: ***@***.***&gt;; 
抄送: "系要听Rock &amp; ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [YeRen123455/Infrared-Small-Target-Detection] NUDT-SIRST 会公开吗？ (Issue #10)





 
我仔细翻看了实验记录，取得77%左右的mIoU是不困难的，NUAA-SIRST 数据集比较小，1~2%的波动很正常，建议采用原文默认实验设置。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lchunleo** [comment]
是否可以在gdrive中提供数据集 (NUDT-SIRST)? 谢谢
