### ISSUE TITLE
李同学您好 请问可以公开您在DNANet中 用于对比的模型的代码吗

### ISSUE THREAD

**Issue by ZhuangChen25674** [YeRen123455/Infrared-Small-Target-Detection#13]
李同学您好:<br>
    我目前同样正在研究红外小目标检测的相关问题, 看到您预印的DNANet后我感到十分振奋, 这真是一项极具创造性的工作, 祝您论文投稿顺利.<br>
    拜读您的工作后, 我深感作为一名研一学子, 基础尚不扎实, 因此打算先行学习比较久远的工作如: ACM ALCNet等模型. 可是这些模型的作者戴博士习惯使用MXNET, 这对于习惯Pytorch的我而言造成了十足的困扰. <br>
    幸而在阅读您论文时发现您竟然使用Pytorch对这些模型进行了复现! 这真的让我意外之余, 倍感惊喜. 然而在模型文件夹内, 我发现只能找到DNANet的模型, 这让我有些沮丧. <br>
    因此冒昧来信, 希望能够获得您论文中对比模型的Pytorch版本的实现, 如能回复, 不胜感激!<br>
    再次感谢您在红外小目标目标领域内的工作,  以及您热爱&&共享的开源精神，这为同样研究这个问题的我们提供了宝贵的思路与优质数据集.<br>
    陈壮

**Comment by YeRen123455** [comment]
你好，近期我们会统一整理所有代表性工作的复现代码，请持续关注。
