### ISSUE TITLE
数据集，训练模型问题，

### ISSUE THREAD

**Issue by 9525** [YeRen123455/Infrared-Small-Target-Detection#14]
您好，我这边运行默认训练的时候，提示：No such file or directory: 'dataset//NUDT-SIRST/images/000282.png'  这个数据集 是不是自动下载的吗？怎么处理啊，可否发我一份到邮箱啊 15527803769@163.com

**Comment by YeRen123455** [comment]
你好，请关注repo内的相关数据集链接
