### ISSUE TITLE
deep_supervision默认为True，但论文里结构为False

### ISSUE THREAD

**Issue by kiwncia** [YeRen123455/Infrared-Small-Target-Detection#15]
您好，感谢您为这个领域做出的贡献并将代码开源，在研读您代码和论文过程中发现deep_supervision这个参数默认为True的话是将得到特征图分别遍历求loss，但在论文的整体架构图中对应的应该是False，只对融合后的特征图求loss，请问这个参数对性能影响大吗。

**Comment by YeRen123455** [comment]
感谢您的善意提醒，论文中只是示意图，deep_supervision在U-shape结构中是一种常见做法，所以没有特意点出。我记得在mIoU上的表现大概有百分之零点几的差别，具体差异您可以自己尝试复现比较。如果代码对您有帮助，麻烦您在论文中引用并帮忙推广，非常感谢。







在 2022-04-25 16:27:35，"哈拉哨" ***@***.***> 写道：

您好，感谢您为这个领域做出的贡献并将代码开源，在研读您代码和论文过程中发现deep_supervision这个参数默认为True的话是将得到特征图分别遍历求loss，但在论文的整体架构图中对应的应该是False，只对融合后的特征图求loss，请问这个参数对性能影响大吗。
