### ISSUE TITLE
定量结果分析的问题

### ISSUE THREAD

**Issue by huzhihen** [YeRen123455/Infrared-Small-Target-Detection#16]
作者你好，我想请问一些问题，在你的Quantative Results中有两个DNANet-ResNet-18，而且得到的性能指标也不相同，所以我想请问这两个之间的区别在哪里？为什么一个DNANet-ResNet-18的mIOU效果会比另一个的mIOU效果好这么多？

**Comment by YeRen123455** [comment]
不好意思，我没太听懂您的问题，可以明确一下具体的图表号或者章节。
















在 2022-05-02 16:42:10，"huzhihen" ***@***.***> 写道：

作者你好，我想请问一些问题，在你的Quantative Results中有两个DNANet-ResNet-18，而且得到的性能指标也不相同，所以我想请问这两个之间的区别在哪里？为什么一个DNANet-ResNet-18的mIOU效果会比另一个的mIOU效果好这么多？

**Comment by YeRen123455** [comment]
因为有些原始模型文件丢失了，找了一个近似结果的模型替代，如果用于对比实验的话建议对照原文来取值。
















在 2022-05-04 22:40:24，"huzhihen" ***@***.***> 写道：

就是在你的 README 中的 Quantative Results 展示的两个表格：on NUDT-SIRST 表格和 on NUAA-SIRST 表格，这两个表格中分别都有两个DNANet-ResNet-18的model，它们的mIOU、Pd、Fa结果是不同的，我想请问为什么不同呢？
