### ISSUE TITLE
您好同学，想请教一下最后的Eight-conneted Neighborhood模块具体作用是做什么呢？

### ISSUE THREAD

**Issue by wcyjerry** [YeRen123455/Infrared-Small-Target-Detection#17]
您好同学，想请教一下最后的Eight-conneted Neighborhood模块具体作用是做什么呢？只是用来计算评价指标的时候用到吗，因为看到跟整个训练过程并没有关系

**Comment by zhahu315** [comment]
类似形态学的膨胀操作，将结果进行邻域的一个合并，比如分割出来的一团目标周围有一些离散目标点或者空隙，这个操作可以把他们合并到领域的一整块目标中，是一个单独的后处理模块

**Comment by YeRen123455** [comment]
是的，主要用于计算检测率和虚警率



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月18日 21:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [YeRen123455/Infrared-Small-Target-Detection] 您好同学，想请教一下最后的Eight-conneted Neighborhood模块具体作用是做什么呢？ (Issue #17) |

这个跟最后指标的计算有关吗





------------------ 原始邮件 ------------------
发件人: Zhang Chi ***@***.***&gt;
发送时间: 2022年7月18日 19:24
收件人: YeRen123455/Infrared-Small-Target-Detection ***@***.***&gt;
抄送: q671383789 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [YeRen123455/Infrared-Small-Target-Detection] 您好同学，想请教一下最后的Eight-conneted Neighborhood模块具体作用是做什么呢？ (Issue #17)






类似形态学的膨胀操作，将结果进行邻域的一个合并，比如分割出来的一团目标周围有一些离散目标点或者空隙，这个操作可以把他们合并到领域的一整块目标中，是一个单独的后处理模块

**Comment by YeRen123455** [comment]
主要起到聚类作用，不参与训练。对pd和fa的评估以及面向后端的目标定位有意义。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年05月10日 17:47 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] 您好同学，想请教一下最后的Eight-conneted Neighborhood模块具体作用是做什么呢？ (Issue #17) |

您好同学，想请教一下最后的Eight-conneted Neighborhood模块具体作用是做什么呢？只是用来计算评价指标的时候用到吗，因为看到跟整个训练过程并没有关系
