### ISSUE TITLE
您好，请问Quantative Results表格中给出的三个预训练模型是分别在三个数据集上训练得到的吗？

### ISSUE THREAD

**Issue by szw811** [YeRen123455/Infrared-Small-Target-Detection#20]
请问表格里给出的三个预训练模型是分别在三个数据集上训练得到的吗？仓库中的pretrain_DNANet_model.tar又是在什么数据集上训练的呢？

**Comment by YeRen123455** [comment]
是的，请以表格中的训练模型为准。仓库中的pretrain_DNANet_model.tar只是为了演示随机挑选的一个过程模型，不能作为模型性能的判断依据。







在 2022-07-15 09:58:34，"szw" ***@***.***> 写道：

请问表格里给出的三个预训练模型是分别在三个数据集上训练得到的吗？仓库中的pretrain_DNANet_model.tar又是在什么数据集上训练的呢？
