### ISSUE TITLE
训练集和测试集的划分

### ISSUE THREAD

**Issue by jzchenriver** [YeRen123455/Infrared-Small-Target-Detection#21]
原文中训练集和测试集的比例是1:1，但在NUDT-SIRST数据集中只提供了全部的images和masks，作者能否提供训练集和测试集的划分文件？谢谢！

**Comment by YeRen123455** [comment]
你好，感谢关注。repo里自带的dataset-nudtsirst-50_50 路径下有训练和测试集的划分依据。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月17日 15:54 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] 训练集和测试集的划分 (Issue #21) |

原文中训练集和测试集的比例是1:1，但在NUDT-SIRST数据集中只提供了全部的images和masks，作者能否提供训练集和测试集的划分文件？谢谢！
