### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by Lliu666** [YeRen123455/Infrared-Small-Target-Detection#22]
GitHub给出的数据集链接过期了，请问能不能更新一下数据集链接

**Comment by YeRen123455** [comment]
你好，最新链接已经更新，感谢关注。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月12日 20:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] 数据集问题 (Issue #22) |

GitHub给出的数据集链接过期了，请问能不能更新一下数据集链接
