### ISSUE TITLE
No module named 'model.model_ACM'

### ISSUE THREAD

**Issue by Alexandic** [YeRen123455/Infrared-Small-Target-Detection#23]
请问作者，这个文件在哪下载？

**Comment by YeRen123455** [comment]
你好，该字段可以直接注销掉，然后可以正常运行。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年09月22日 10:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] No module named 'model.model_ACM' (Issue #23) |

请问作者，这个文件在哪下载？
