### ISSUE TITLE
1

### ISSUE THREAD

**Issue by yangdali1** [YeRen123455/Infrared-Small-Target-Detection#25]
请问您提出的NUDT-sirst 数据集1327张图片里包含多少个小目标呢？

**Comment by YeRen123455** [comment]
请参见最新版Figure6， 有96%左右的目标符合小目标定义。




在 2022-10-17 16:06:58，"yangdali1" ***@***.***> 写道：

请问您提出的NUDT-sirst 数据集1327张图片里包含多少个小目标呢？
