### ISSUE TITLE
关于训练的问题

### ISSUE THREAD

**Issue by SHR1103** [YeRen123455/Infrared-Small-Target-Detection#27]
你好，我想问一下训练突然中断了，如何从中断的地方接着训练呀？

**Comment by YeRen123455** [comment]
你好，暂时没有这个功能。模型是自动保存的，可以重新load一下。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年11月03日 14:13 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] 关于训练的问题 (Issue #27) |

你好，我想问一下训练突然中断了，如何从中断的地方接着训练呀？
