### ISSUE TITLE
关于复现效果的问题

### ISSUE THREAD

**Issue by 1071189147** [YeRen123455/Infrared-Small-Target-Detection#30]
您好，十分感谢您的代码，我使用NUDT数据集，也是单块3090，按照您给定的参数，原始代码没有修改，多次训练，最终训练出的结果大概在这个范围：IoU:0.82-0.85之间，Pd在0.97-0.985之间，Fa在7-11 ×10^-6, 无法训练到您的效果。请问您觉得可能是哪方面的问题吗？

**Comment by YeRen123455** [comment]
你好，0.89的IoU是在中科大云服务器上取得的最高值，因此我们并没有在论文中体现，仅放出模型参数供大家参考。0.86左右的IoU是可以多次获得的，建议您采用固定的学习率，deep supervision =True，然后再重复训练几次。

**Comment by 1071189147** [comment]
给后面的同志们提醒一下，可以把epoch弄得多一点，基本可以复现到作者的效果。我一看损失基本稳定了就停了，但其实效果还可以更好。
