### ISSUE TITLE
关于The Eight-connected Neighborhood Clustering Module 算法

### ISSUE THREAD

**Issue by ShunshunZhong** [YeRen123455/Infrared-Small-Target-Detection#31]
你好，在你公开的代码中好像没找到该算法的代码。不知道是我的问题，还是程序不全吗？

**Comment by EdwardBao1006** [comment]
我好像也没看到，我还以为是我弄错了。

**Comment by YeRen123455** [comment]
你好，聚类的代码在求解pd和fa的部分。



---- 回复的原邮件 ----
| 发件人 | Edward ***@***.***> |
| 日期 | 2023年03月02日 15:24 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [YeRen123455/Infrared-Small-Target-Detection] 关于The Eight-connected Neighborhood Clustering Module 算法 (Issue #31) |

我好像也没看到，我还以为是我弄错了。
