### ISSUE TITLE
NUDT-SIRST数据集

### ISSUE THREAD

**Issue by GangPingZ** [YeRen123455/Infrared-Small-Target-Detection#34]
作者你好！我通过给的链接下载的NUDT-SIRST数据集中只有images和masks，为什么会没有标签文件呢？

**Comment by YeRen123455** [comment]
你好，已经嵌在训练文件内了。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月03日 00:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] NUDT-SIRST数据集 (Issue #34) |

作者你好！我通过给的链接下载的NUDT-SIRST数据集中只有images和masks，为什么会没有标签文件呢？

**Comment by GangPingZ** [comment]
好的谢谢！
