### ISSUE TITLE
论文问题请教

### ISSUE THREAD

**Issue by Joazs** [YeRen123455/Infrared-Small-Target-Detection#35]
您好，关于您论文中的Table VII我有个问题。
实验结果Table VII中显示，在NUAA-SIRST数据集上，DNANet的IoU指标是77.47。请问这个指标结果是NUAA原来数据集的划分吗？
NUAA-SIRST的划分是256train,85val,86test。这个结果是按照它的划分出现的测试结果吗？还是按照您自己的划分方法所出来的结果？

**Comment by YeRen123455** [comment]
你好，是按照本论文的划分方式，同ACM论文的划分方式不一致。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年02月24日 13:39 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] 论文问题请教 (Issue #35) |

您好，关于您论文中的Table VII我有个问题。
实验结果Table VII中显示，在NUAA-SIRST数据集上，DNANet的IoU指标是77.47。请问这个指标结果是NUAA原来数据集的划分吗？
NUAA-SIRST的划分是256train,85val,86test。这个结果是按照它的划分出现的测试结果吗？还是按照您自己的划分方法所出来的结果？
