### ISSUE TITLE
about the learning rate

### ISSUE THREAD

**Issue by cannonli7** [YeRen123455/Infrared-Small-Target-Detection#39]
你好，请问代码里面，学习率是不是没变？epoch结束以后，好像没有加上schedule.step()

**Comment by YeRen123455** [comment]
这一行是注释掉的，采用固定学习率。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月16日 15:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] about the learning rate (Issue #39) |

你好，请问代码里面，学习率是不是没变？epoch结束以后，好像没有加上schedule.step()

**Comment by cannonli7** [comment]
好的，谢谢



在 2023-03-16 17:03:17，"Boye" ***@***.***> 写道：

这一行是注释掉的，采用固定学习率。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月16日 15:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] about the learning rate (Issue #39) |

你好，请问代码里面，学习率是不是没变？epoch结束以后，好像没有加上schedule.step()
