### ISSUE TITLE
where is the model.model_ACM?

### ISSUE THREAD

**Issue by Lihang0003** [YeRen123455/Infrared-Small-Target-Detection#4]
We can comment the code: from model.model_ACM import ACM, and avoid the ACM method tests.But we still want to ask where is the model_ACM.py or when is available?

**Comment by YeRen123455** [comment]
You can delete it. If you want to test on ACM, I suggest you refer to the link https://github.com/YimianDai/open-acm

**Comment by Lihang0003** [comment]
> You can delete it. If you want to test on ACM, I suggest you refer to the link https://github.com/YimianDai/open-acm

Thanks !
