### ISSUE TITLE
关于对比实验问题

### ISSUE THREAD

**Issue by yang19950411** [YeRen123455/Infrared-Small-Target-Detection#41]
您好！您在做对比实验时，是对所有方法进行了复现吗？论文中提到提供了对比方法的代码，但是我好像没有找到相关代码，可以提供对比用的代码吗？感谢，感谢！！！

**Comment by YeRen123455** [comment]
你好，正式版论文里已经没有相关表述。为了避免实验偏差，我们最终没用此方案。



---- 回复的原邮件 ----
| 发件人 | Yang ***@***.***> |
| 日期 | 2023年04月05日 10:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] 关于对比实验问题 (Issue #41) |

您好！您在做对比实验时，是对所有方法进行了复现吗？论文中提到提供了对比方法的代码，但是我好像没有找到相关代码，可以提供对比用的代码吗？感谢，感谢！！！

**Comment by yang19950411** [comment]
![Z9_)%R{ G_Z2J AOH){WZMP](https://user-images.githubusercontent.com/88123195/230273279-648bbd23-09b8-4d52-b9bf-450fdc81cba1.png)

**Comment by yang19950411** [comment]
![Z9_)%R{ G_Z2J AOH){WZMP](https://user-images.githubusercontent.com/88123195/230273301-4de4dff0-0bf4-45d7-be58-26b1f483fde2.png)
我对论文中此部分的理解是，复现了其他方法，并在相同的数据集上进行了对比，并且提供了其他方法的源码，是我理解不当吗？想请教下您是怎么做对比实验的

**Comment by YeRen123455** [comment]
你好，最终版论文的实验结果是依照各个对比算法原文公开的源码重新训练得到的。例如，我们重新配置了MXNet来复现ACM和ALCNet。



---- 回复的原邮件 ----
| 发件人 | Yang ***@***.***> |
| 日期 | 2023年04月06日 12:40 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [YeRen123455/Infrared-Small-Target-Detection] 关于对比实验问题 (Issue #41) |


我对论文中此部分的理解是，复现了其他方法，并在相同的数据集上进行了对比，并且提供了其他方法的源码，是我理解不当吗？想请教下您是怎么做对比实验的

**Comment by yang19950411** [comment]
好的，明白了，感谢

**Comment by yang19950411** [comment]
作者您好，还有个问题想请教下。就是您对比的模型当中，有些模型是有开源代码的，但是也有一部分似乎并没有开源的代码，比如一些传统的方法。想问下您是怎么对这些模型进行复现并得到它们的评价指标的，因为我也想做对比实验，但是您论文中提到的一些模型，我不知道如何复现，也不知道怎么得到它们的评价指标，希望您能帮我解惑

**Comment by LittleFelicia** [comment]
> 作者您好，还有个问题想请教下。就是您对比的模型当中，有些模型是有开源代码的，但是也有一部分似乎并没有开源的代码，比如一些传统的方法。想问下您是怎么对这些模型进行复现并得到它们的评价指标的，因为我也想做对比实验，但是您论文中提到的一些模型，我不知道如何复现，也不知道怎么得到它们的评价指标，希望您能帮我解惑

请问最后您是怎么复现的这些对比实验的方法的呢？
