### ISSUE TITLE
模型对比效果

### ISSUE THREAD

**Issue by yang19950411** [YeRen123455/Infrared-Small-Target-Detection#44]
可以开源对比模型代码吗？

**Comment by YeRen123455** [comment]
您好，我们可以在您获得这些代码后进行参数共享，但是很难公开除本文算法代码之外的内容。因为我们很难在不经过他人授意的前提下分享这些代码，这可能会牵扯到知识产权问题。



---- 回复的原邮件 ----
| 发件人 | Yang ***@***.***> |
| 日期 | 2023年04月13日 09:23 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [YeRen123455/Infrared-Small-Target-Detection] 模型对比效果 (Issue #44) |

可以开源对比模型代码吗？

**Comment by yang19950411** [comment]
好的，明白，感谢！！！
